### ISSUE TITLE
The HTTP request is unauthorized with client authentication scheme 'Ntlm'. The authentication header received from the server was 'NTLM'.

### ISSUE THREAD

**Issue by jk1510karti** [braathen/qv-edx-trigger#10]
Hi Team,

I am using QvEDX Trigger, while triggering task im getting below error.
"The HTTP request is unauthorized with client authentication scheme 'Ntlm'. The authentication header received from the server was 'NTLM'."

I understand that, user must be in QMS local group, but Is there any way that, I could embed the credentials in "QvEDXTigger.exe.config" file. ? Or in runtime how can i provide the credentials. ?

Its quite urgent. Appreciate your help.

**Comment by braathen** [comment]
Sorry, the process calling the application needs to use Windows Authentication (NTLM) and be part of the QlikView Management API group.

**Comment by jk1510karti** [comment]
How can I add the user into QlikView Management API Group ?

Is there any other method available to pass the credentials in config file or in run time. ?

**Comment by braathen** [comment]
The user is added through Windows management...
https://technet.microsoft.com/en-us/library/cc772524(v=ws.11).aspx

No other way.

**Comment by jk1510karti** [comment]
Thank you so much @braathen

**Comment by jk1510karti** [comment]
Hi @braathen sorry to re-open the issue, I have added the user into QlikView Management API, But still im unable to access the task, im getting same error while executing .\QvEDXTrigger.exe -task="example"

I have modified the QvEDXTrigger.exe.config to my server URL

**Comment by braathen** [comment]
And what error are you getting?

**Comment by jk1510karti** [comment]
The below error:

ERROR: The HTTP request is unauthorized with client authentication scheme 'Ntlm'. The authentication header received from the server was 'NTLM'. (Error code:10)

**Comment by braathen** [comment]
OK, I'm sorry but I don't know what you're doing wrong. I haven't worked with QlikView for 3 years and don't have an environment to look into this. Maybe try this app instead...

https://community.qlik.com/docs/DOC-2650

**Comment by jk1510karti** [comment]
Hi @braathen  This time im getting ERROR|Unrecognized message version. (Error code:10)

Actuall when I try to access my QV server http://example.com:4780/qmc/, it will prompt for the NTLM authentication.  I have given the same UTL in QvEDXTrigger.exe.config file. is that correct ?

**Comment by braathen** [comment]
Please try the other app on the website I mentioned before instead. I cannot support this application any longer. I have no idea what you are doing wrong.
