### ISSUE TITLE
is it possible to pass several parameters ?

### ISSUE THREAD

**Issue by alexandgithub** [braathen/qv-edx-trigger#11]
hello

is it possible to pass several parameters ?

**Comment by braathen** [comment]
what do you mean?

**Comment by alexandgithub** [comment]
you said:
"Trigger a task with custom variable name and values:
QvEDXTrigger.exe --task="Reload and distribute this fantastic task" --variable=Numbers --values=1;2;3;4;5"

so 
is it possible to pass like
QvEDXTrigger.exe --task="someTask" --variable=param1 --values=1;2;3;4;5 --variable=param2 --values=100500

?

**Comment by braathen** [comment]
Ah, ok... That's not supported unfortunately, it should probably have been, but I didn't think about it 5 years ago and unfortunately have no possibility to update or maintain this project myself anymore. Sorry....

**Comment by alexandgithub** [comment]
Not a problem. Thanks for replies.
