### ISSUE TITLE
downloaded zip file not having .exe file

### ISSUE THREAD

**Issue by Shanmuga01** [braathen/qv-edx-trigger#12]
Hi,

I have downloaded the zip file and found there is no .exe/setup file to install.

Not sure if I'm checking it wrongly, please guide me.

Thanks,
Shan S

**Comment by Shanmuga01** [comment]
@braathen

Can you please help here.

-Shan S

**Comment by braathen** [comment]
this is a source code repository only, you need to compile it using Visual Studio.
