### ISSUE TITLE
Task Name in publisher, misspelled, causes Error 10

### ISSUE THREAD

**Issue by xqjibz** [braathen/qv-edx-trigger#4]
Is there any way to capture this beyond Error 10?  We had a misnamed publisher task, and it brought back an error 10 vs not found.  What I'm wondering, is there a way to capture 'not found' vs the generic below.

```
C:\epapps\bin>QvEDXTrigger.exe --task="Booking vs. Forecast Weekly Report" --ser
vice="http://QVSERV03:4799/QMS/Service" --timeout=300
10:54:43.8026|ERROR|Index was out of range. Must be non-negative and less than t
he size of the collection. Parameter name: index (Error code: 10)
```

**Comment by braathen** [comment]
I'm not sure, I think the program more or less returns what is given to it.. maybe it could be handled in some way though.

Please try this updated binary build if you haven't already. It's not doing anything to your specific problem above, but it avoids a lot of those error 10's...

https://dl.dropboxusercontent.com/u/691880/qv-edx-trigger-20140610.zip

**Comment by xqjibz** [comment]
@braathen that's good news then, I'll update the trigger.  And I was more wondering out loud about the naming issue, I mean, honestly speaking, there should not be a time when you're attempting to run one that isn't named properly. :)

I am closing the issue, and we'll update here in the near future.
