### ISSUE TITLE
Task Not Found (Error code:9)

### ISSUE THREAD

**Issue by Bhardin04** [braathen/qv-edx-trigger#5]
I have tried to use both the task ID and the task name but I get the same error.  I checked in ProgramData\Qliktech\DistributionService\Task to find the XML file for the task but I can't figure out what the issue.

![2015-05-22_8-08-17](https://cloud.githubusercontent.com/assets/11240858/7771044/171651f4-005a-11e5-93aa-05238ddae922.png)

**Comment by braathen** [comment]
Did you enable the task as external trigger in qmc?
