### ISSUE TITLE
QlikView 12

### ISSUE THREAD

**Issue by hrolofs** [braathen/qv-edx-trigger#6]
Hello,

after an upgrade to QV 12 we got this error messages.

12:49:47.0999|ERROR|The message with Action 'http://ws.qliktech.com/QMS/11/IQMS/GetTimeLimitedServiceKey' cannot be processed at the receiver, due to a ContractFilter mismatch at the EndpointDispatcher. This may be because of either a contract mismatch (mismatched Actions between sender and receiver) or a binding/security mismatch between the sender and the receiver.  Check that sender and receiver have the same contract and the same binding (including security requirements, e.g. Message, Transport, None). (Error code: 10)

if it's possible that this helpfull program can work with QV12?

Regards, Henry

**Comment by braathen** [comment]
Hi Henry, I think it should be fairly easy to get it running with QV12, it more or less only needs to be recompiled against the QV12 service reference and/or update the app.config. I did this for one of my other repositories recently, will see if I can find time to do it early next week.

**Comment by hrolofs** [comment]
Hi Rikard,

thanks for this info. :-)

**Comment by hrolofs** [comment]
Hello Rikard,

i have compiled your source with an update of the QMSAPI.Service Reference. I delete the two additional new endpoint entries in the app.config and rebuild the project. Copied the 7 files from the bin/debug folder (all except the vshost files) to the QV Server.

And it works :-)

**Comment by braathen** [comment]
Great work! :) thx for letting me know!

**Comment by seebach** [comment]
Any chance for sharing this update? I've hit the same error.

**Comment by seebach** [comment]
Found a working versions: https://community.qlik.com/docs/DOC-5111
