### ISSUE TITLE
Variable Values which have comas

### ISSUE THREAD

**Issue by oscar-ivan** [braathen/qv-edx-trigger#7]
Hi
I have been using it, and it it working fine so far.
I need to pass a value into a variable but this value includes comas.
Seems that the variable only receive the past of the value before the coma.
I have tried using "" and '' but it does not work
So how can pass the entire value to the variable?
Cheers
Oscar

**Comment by oscar-ivan** [comment]
By the way , how can be pass the value to more than one variable?

**Comment by braathen** [comment]
Unfortunately the way it's built the value parameter may be separated by semicolon or commas, which means your commas will work as separators. You will need to modiify the code below and remove the comma to make it work.

v =>t.VariableValues = new List<string>(v.Split(new[] {';', ','}, StringSplitOptions.RemoveEmptyEntries))
