### ISSUE TITLE
Message inspection failed | Error Code 10

### ISSUE THREAD

**Issue by acs1980** [braathen/qv-edx-trigger#8]
Hi Braathen,
I would like to request you to advise me on this issue please.

When we call a QMC task through external scheduler Control M via QvEDXTrigger, I am getting the issue whereby Contrl M job failed with error "Message inspection failed | Error Code 10". But when I check in QMC, the task was not triggered. I am facing this issue after upgrade to QV11 SR13 from QV11 SR12. 

Can you please advise on this?

Thanks,
Chan

**Comment by braathen** [comment]
Hi Chan,

I looked in our support database, below is a cut from it so you can understand the problem... although I want to help you, it does seem as there will be some changes and a lot of testing needed to get this sorted and unfortunately I don't have an environment to do that at this time, but what's even worse is that I'm also on vacation during entire July. I will try my best to set up an environment and replicate the issue today and see if there's an easy fix...

**Cause**

This error occurs when the Service Key provided to the API is under verification. The QMS tries to extract a property called Name which returns NULL (when it expects the Service Key).

This error can occur if not allowing enough time between each step in the client code. E.g. Creating the source document and immediately calling the APIs to create an associated task for it.

**Resolution**

The issue can be resolved by implementing a sleep thread that checks for a documents existence before creating the task. This also results in the custom code calling the API fewer times. 

More time should be allowed between each step. E.g. Creating the source document and allowing some time before calling on the APIs to create an associated task for it.

**Comment by braathen** [comment]
Meanwhile... Please try this latest version and add the --wait parameter and some seconds before executing the task. Maybe it helps...

https://dl.dropboxusercontent.com/u/691880/qv-edx-trigger-20150907.zip

**Comment by acs1980** [comment]
Great Braathen. Thanks a lot. You are really awesome. I will try and let you know the outcome.
