### ISSUE TITLE
The QlikVIEw EDX trigger exe is holding lock on batch script that it is triggered from external scheduler.

### ISSUE THREAD

**Issue by Damodar1988** [braathen/qv-edx-trigger#9]
EDX trigger exe is holding lock on batch script that it is triggered from external scheduler.

This EDX file was downloaded from below location.

https://dl.dropboxusercontent.com/u/691880/qv-edx-trigger-20150907.zip

**Comment by braathen** [comment]
This tool waits for the task execution to finish, if it for some reason doesn't it get's difficult to terminate in some other way. It has run successfully for a number of large installations for 3-4 years though, so I don't know what might have changed.

I would recommend trying this other tool, which works in a similar way, but doesn't wait for the task to finish.

https://community.qlik.com/docs/DOC-2650

I have no possibility to support this tool, and it's published here more as a code example to get started or learn from.
